### ISSUE TITLE
Design - Import from Github File

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-extended-app#120]
- [x] To choose a JS lib to handle github calls.
- [x] How to connect to GitHub
- [x] Provide estimation in hours. Min/max no python just the app.
------

TBC Task:
- [ ] New option in Import/Export Menu: 'Import from Github File'
- [ ] Settings
   - [ ] Hide for users that can't create users
   - [ ] Parameters:
      - [ ] Github url. It can be prefilled with the info read from config file.
      - [ ] Branch. One branch per server: preproduction and training.
      - [ ] User/Pw: Maybe a token? Connect to Github? Cookie?
      - [ ] Dropdown: push every import or ask every import 
- [ ] Upload JSON and CSV file to Github if success

**Comment by tokland** [comment]
-  Githut API JS: The most popular libraries are https://github.com/github-tools/github and https://github.com/octokit/rest.js. octokit/rest.js is the official app and has tons of features, so I started there. It worked just fine, I tested: authorize + createFile OR updateFile.

- How to connect to github: Docs: https://developer.github.com/v3/guides/basics-of-authentication. Problem: a  purely client-side workflow is not supported by github (for security reasons). The conversion from the callback URL *code* to a real *token* must be performed in a server (otherwise you'll expose the app secret key in the JS code). That's why projects like this exist: https://github.com/prose/gatekeeper (tested, worked fine). So to sum it, to have a web-flow authoritzation: 1) we need to create a Oauth app in github, 2) Deploy a server somewhere (dev.est?) with gatekeeper. 3) Use octokit/rest.js in the React app to commit to github. Other options (having tokens directly in the JS code) have the same problem, we're exposing sensitive data.

**Comment by ifoche** [comment]
@tokland answered via Slack, but just to leave a trace here... I'm wondering how octokit would manage conflicts when pushing a file that's been modified since you got it...actually would it recognize those corner cases at all?

**Comment by adrianq** [comment]
Moving back to ready. We will review this card and convert it into an 'implementation card'

**Comment by adrianq** [comment]
Moved to clickup
